<?php echo $this->doctype(); ?>
<?php header("Content-Type: text/html; charset=utf-8"); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle(\RssExtend\Version::NAME)->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <?php echo $this->headLink(array(
                                    'rel' => 'shortcut icon',
                                    'type' => 'image/vnd.microsoft.icon',
                                    'href' => $this->basePath() . '/images/favicon.ico'
                               ))->prependStylesheet('/css/jquery.mobile.min.css'); ?>

    <?php echo $this->headScript()->prependFile('/js/jquery.mobile.min.js')
    ->prependFile($this->basePath() . '/js/jquery.min.js')
    ?>

</head>
<body>
<div data-role="page">
    <?php echo $this->content; ?>
</div>
<!-- /container -->
<?php echo $this->inlineScript() ?>
</body>
</html>