<?php echo $this->doctype(); ?>
<?php header("Content-Type: text/html; charset=utf-8"); ?>

<html>
<head>
    <?php echo $this->headTitle(\RssExtend\Version::NAME)->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <?php echo $this->headLink(array(
                                    'rel' => 'shortcut icon',
                                    'type' => 'image/vnd.microsoft.icon',
                                    'href' => $this->basePath() . '/images/favicon.ico'
                               ))->prependStylesheet('/bootstrap/css/starter-template.css')->prependStylesheet('/bootstrap/css/bootstrap-theme.css')
        ->prependStylesheet('/bootstrap/css/bootstrap.css') ->prependStylesheet('/css/font-awesome.css'); ?>

    <?php echo $this->headScript()->prependFile('/js/rssextend.js')->prependFile('/bootstrap/js/bootstrap.min.js')->prependFile('/js/jquery.min.js'); ?>


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="/"><?php echo \RssExtend\Version::NAME; ?></a>
        </div>

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="/#list"><?php echo $this->translate('Feeds'); ?></a></li>
            </ul>
        </div>

    </div>
</div>

<?php echo $this->content; ?>
</body>
</html>